server:
  port: "8001"
spring:
  cloud:
    consul:
      discovery:
        instanceId: ms-service-a
        health-check-interval: 5s
service:
  b:
    url: http://ms-service-b/service/b

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      aInformation:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - com.jb.msservicea.exceptions.CustomException
  retry:
    instances:
      aInformation:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      aInformation:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefresheriod: 10s
        timeoutDuration: 3s
